SPLE Platform Glossary and Architecture
avengineers/spl-core pull request #121
Opened 2024-03-27 13:54 UTC by xxthunder

2024-03-27 15:53 UTC, GabrielaMichelon approved these changes

2024-03-28 13:13 UTC, LeMollinger requested changes
I only discovered two small details. Everything else looks very good.

2024-03-28 13:13 UTC, LeMollinger commented on docs/getting_started/glossary.rst
> +Snapshot
The alphabetical order of the terms got a little mixed up here.

2024-03-28 13:13 UTC, LeMollinger commented on docs/getting_started/glossary.rst
> +A pipeline is a directed graph of steps with a single entry point and a single exit point. The steps are executed in a specific order.
Here it would be fitting to link the glossary entry to the steps:
```suggestion
A pipeline is a directed graph of  :ref:`steps <glossary_step>` with a single entry point and a single exit point. The :ref:`steps <glossary_step>` are executed in a specific order.
```

2024-04-16 18:50 UTC, merged