PSScriptAnalyzer linter changes
avengineers/spl-core pull request #30
Opened 2023-01-20 13:33 UTC by besessener

`Install-Module -Name PSScriptAnalyzer -Force` is required to locally install it if missing.
PSScriptAnalyzer will act as a powershell linter on both productive and test sources.
All deviations got resolved, only one was resolved by writing a justification.

2023-01-20 14:31 UTC, xxthunder commented on powershell/spl-functions.ps1
>              & $PSScriptRoot\install-scoop.ps1 -RunAsAdmin
```suggestion
            & "$PSScriptRoot\install-scoop.ps1" -RunAsAdmin

```

2023-01-20 14:31 UTC, xxthunder commented on powershell/spl-functions.ps1
>              & $PSScriptRoot\install-scoop.ps1 -RunAsAdmin
Please do this everywhere to handle spaces in $PSScriptRoot

2023-01-20 14:36 UTC, xxthunder requested changes
🦆

2023-01-24 16:30 UTC, besessener commented
as We saw a bug for installing dependencies, this PR is also adding a new way of installing scoop packages with Scoopfile.json.

2023-02-01 13:14 UTC, closed without merging